### ISSUE TITLE
class error in wdpa_clean

### ISSUE THREAD

**Issue by JonasGeschke** [prioritizr/wdpar#19] opened 2020-02-18 11:18 UTC
After trying around with the `sp` package for quite a bit, I will now try to flatten the WDPA with `wdpar`. The first error I came across, however, is as follows:

> Error in st_cast_sfc_default(x) : list item(s) not of class sfg

It came in the WDPA subset for "SOM" (Somalia). Would be great if you can have a look at it.
Thanks and best regards,
Jonas

**Comment by JonasGeschke** [comment] 2020-02-18 11:18
PS: Are you around at the sri2020.org conference? Would be great meeting you.

**Comment by jeffreyhanson** [comment] 2020-02-18 20:31
Hmm - that's strange. Could you please post a reproducible example showing this? Are you using `as(x, "sf")` to convert the `sp` class objects to `sf` class objects before using `wdpa_clean`?

No, I'm not attending that conference unfortunately - it looks pretty interesting! Yeah - it would be great to catch up. I'm based in Palmerston North in New Zealand - I don't suppose you're travelling to New Zealand while you're in the region?

**Comment by JonasGeschke** [comment] 2020-02-19 09:32
Well no I didnt convert the WDPA from `sp` to `sf`, I read the WDPA with `wdpar`:

> wdpa <- wdpa_read("~/WDPA_Feb2020-shapefile.zip")
wdpa <- wdpa[-which(wdpa$MARINE == "2"),]
wdpa <- wdpa[-which(wdpa$ISO3 == "ABNJ"),]
wdpa_som <- wdpa[which(wdpa$ISO3 == "SOM"),]
wdpa_som <- wdpa_clean(wdpa_som)

<img width="487" alt="Bildschirmfoto 2020-02-19 um 10 30 41" src="https://user-images.githubusercontent.com/14090764/74820811-eed1fa80-5302-11ea-82a7-dcee24df3ce8.png">
(sorry it is in German, but the error remains the same)

**Comment by JonasGeschke** [comment] 2020-02-21 09:41
update: I now tried to clean SOM with the development version of `wdpar` – it worked. so in case you dont want to follow up on the origin of the error, you may close the issue.

**Comment by JonasGeschke** [comment] 2020-02-21 09:41
its your go to close it ;-)

**Comment by jeffreyhanson** [comment] 2020-02-23 20:40
Great - glad to hear it's working. I'll close this issue now then. In the future, if you feel that you've solved an issue that you've opened, please feel free to close it yourself :)

**Comment by JonasGeschke** [comment] 2020-02-24 14:20
Strange... with a changed precision, the error comes up again. Would be great if you could have a look at it.

> Error in st_cast_sfc_default(x) : list item(s) not of class sfg

**Comment by JonasGeschke** [comment] 2020-03-01 18:01
So this class error still is the bottleneck in my progress...

**Comment by jeffreyhanson** [comment] 2020-03-02 20:50
Per #22, could you please post a complete reproducible example showing the issue you're experiencing?

**Comment by JonasGeschke** [comment] 2020-03-20 10:12
Hi – sorry for not replying yet. You can find the reproducible example above. However, it does not pop up always, I have no clue why. Did you change anything in the development version that could have lead to fixing the class error?

**Comment by JonasGeschke** [comment] 2020-03-27 09:38
Congrats to your [paper](https://www.nature.com/articles/s41586-020-2138-7), very nice reading!

In regard of my work on the WPDA, using `wdpar`: I am in still in progress cleaning and unioning all countries individually and plan to union them together afterwards.
During the computing, the class error came up again – using the development version of the package. Would be great if you find some time working on this error.

**Comment by jeffreyhanson** [comment] 2020-03-27 22:58
Thanks! It looks like the issue with Somalia is that all the protected areas are points and they have a REP_AREA of zero - meaning that there are no "spatially valid non-empty" geometries for this country. I'll add in a patch to return an empty result (i.e. sf object with zero rows) for such cases.

**Closed** 2020-03-28 00:02 UTC

**Comment by jeffreyhanson** [comment] 2020-03-28 00:03
Ok - I've just pushed a new version that works for Somalia. Thanks for the reminder!
